apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: app
  labels:
    manifestType: pod
spec:
  containers:
  - name: app
    image: 009147451403.dkr.ecr.us-east-1.amazonaws.com/prod-app:6491ac94a7b01e0286f7e2c630ef41fcb67aeca2
    env:
        - name: DBHOST
          value: "10.244.0.9"
        - name: DBPORT
          value: "3306"
        - name: DATABASE
          value: "employees"
        - name: DBPWD
          value: "pw"
        - name: DBUSER
          value: "root"
        - name: APP_COLOR
          value: "blue"
    ports:
        - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
